# Generated by Django 2.0.3 on 2018-03-22 12:25

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='СЛУГ')),
                ('small_content', ckeditor_uploader.fields.RichTextUploadingField(max_length=600, verbose_name='краткое содержание')),
                ('deteil_content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Полное содержание')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
