# Generated by Django 2.0.3 on 2018-03-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_news', '0003_auto_20180322_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='deteil_content',
            new_name='detail_content',
        ),
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, upload_to='news', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='news',
            name='small_content',
            field=models.CharField(max_length=500, verbose_name='Краткое содержание'),
        ),
    ]
