# Generated by Django 2.0.3 on 2018-03-13 18:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название каталога')),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталоги',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('slug', models.SlugField(max_length=100)),
                ('is_import', models.BooleanField(default=True, verbose_name='Импортное')),
                ('count', models.SmallIntegerField(default=0, verbose_name='Количество в наличи')),
                ('shelf_life', models.DateField(default=django.utils.timezone.now, verbose_name='Срок годности')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Catalog', verbose_name='Каталога')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
