# Generated by Django 2.0.3 on 2018-03-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180322_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='img',
            field=models.ImageField(blank=True, upload_to='animals', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Кличка'),
        ),
    ]
