# Generated by Django 2.0.2 on 2018-03-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180305_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='article',
            name='news_list',
            field=models.CharField(max_length=200, verbose_name='Описание'),
        ),
    ]
