# Generated by Django 2.0.2 on 2018-03-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180305_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='news_list',
            new_name='news_info',
        ),
    ]
