# Generated by Django 2.0.3 on 2018-03-25 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180325_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='kind',
        ),
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='121212', verbose_name='Слуг'),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.CharField(blank=True, choices=[('о', 'Опасность'), ('g', 'Государство'), ('se', 'Сенсация'), ('sr', 'Срочные')], max_length=2, verbose_name='Теги'),
        ),
    ]
