# Generated by Django 2.0.3 on 2018-03-22 12:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_news', '0002_auto_20180322_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='deteil_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Полное содержание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='small_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=600, verbose_name='краткое содержание'),
        ),
    ]
