# Generated by Django 2.0.2 on 2018-03-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180311_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.CharField(default=None, max_length=50, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.FloatField(default=0.00, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default='1970-01-01'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
