# Generated by Django 2.0.2 on 2018-03-12 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('value', models.CharField(max_length=1028, verbose_name='Value')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('slug', models.SlugField(max_length=100)),
                ('company', models.CharField(default=None, max_length=50, verbose_name='Название компании')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Цена')),
                ('date', models.DateField(default='1970-01-01')),
                ('weight', models.FloatField()),
                ('image', models.ImageField(null=True, upload_to='products/', verbose_name='Фото')),
                ('is_import', models.BooleanField(default=False, verbose_name='Оригинал')),
                ('url', models.URLField(verbose_name='Сайт производителя')),
                ('email', models.EmailField(max_length=254, verbose_name='Маил')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Catalog', verbose_name='Каталог')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товаров',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='catalog',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='options',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products'),
        ),
    ]
